import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    title: "AGV PISTA GP",
    description: "ECE DOT TOP - SOLELUNA 2019",
    price: "104999",
    offer: "20",
    rating: "5",
    categoryName: "Racing",
  },
  {
    _id: uuid(),
    title: "AGV AX8 EVO",
    description: "TRAIL GUNMETAL/ORANGE",
    price: "23999",
    offer: "15",
    rating: "4",
    categoryName: "Off Road",
  },
  {
    _id: uuid(),
    title: "AGV AX9 MULTI",
    description: "ECE DOT TOP - SOLELUNA 2019",
    price: "41999",
    offer: "15",
    rating: "4",
    categoryName: "Off Road",
  },
  {
    _id: uuid(),
    title: "AGV SPORTMODULAR MULTI",
    description: "ECE DOT TOP - SOLELUNA 2019",
    price: "65999",
    offer: "20",
    rating: "5",
    categoryName: "Touring",
  },
  {
    _id: uuid(),
    title: "ARAI GP7",
    description: "(FRP) RACE TESTED",
    price: "71999",
    offer: "10",
    rating: "4",
    categoryName: "Racing",
  },
  {
    _id: uuid(),
    title: "ARAI QUANTIC",
    description: "HIGH-SPEED COMFORT",
    price: "67999",
    offer: "20",
    rating: "4",
    categoryName: "Street",
  },
  {
    _id: uuid(),
    title: "ARAI URBAN-V",
    description: "LOOK COOL. STAY COOL",
    price: "45999",
    offer: "15",
    rating: "3",
    categoryName: "Touring",
  },
  {
    _id: uuid(),
    title: "MT RAPID PRO",
    description: "PRO MASTER B5 GLOSS FLOUR RED",
    price: "27999",
    offer: "15",
    rating: "5",
    categoryName: "Racing",
  },
  {
    _id: uuid(),
    title: "MT TARGO CRAZYDOG",
    description: "CRAZYDOG G3 GLOSS FLOUR YELLOW",
    price: "7899",
    offer: "10",
    rating: "4",
    categoryName: "Street",
  },
  {
    _id: uuid(),
    title: "MT FALCON ENERGY",
    description: "ENERGY B5 GLOSS RED",
    price: "7299",
    offer: "10",
    rating: "5",
    categoryName: "Off Road",
  },
  {
    _id: uuid(),
    title: "MT JET LEMANS",
    description: "TANT A5 MATT RED",
    price: "7599",
    offer: "10",
    rating: "4",
    categoryName: "Touring",
  },
  {
    _id: uuid(),
    title: "SHOEI X-FOURTEEN",
    description: "MATT BLACK",
    price: "59999",
    offer: "20",
    rating: "5",
    categoryName: "Racing",
  },
  {
    _id: uuid(),
    title: "SHOEI VFX EVO",
    description: "MATT BLACK",
    price: "44999",
    offer: "15",
    rating: "4",
    categoryName: "Off Road",
  },
  {
    _id: uuid(),
    title: "SHOEI GT AIR 2",
    description: "MATT BLACK",
    price: "65999",
    offer: "15",
    rating: "5",
    categoryName: "Street",
  },
  {
    _id: uuid(),
    title: "SHOEI RF 1400",
    description: "MATT BLACK",
    price: "55999",
    offer: "15",
    rating: "4",
    categoryName: "Street",
  },
  {
    _id: uuid(),
    title: "SHOEI HORNET X2",
    description: "MATT BLACK",
    price: "38999",
    offer: "15",
    rating: "4",
    categoryName: "Touring",
  },
];
