import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    name: "AGV PISTA GP",
    brand: "agv",
    inStock: true,
    fastDelivery: true,
    description: "ECE DOT TOP - SOLELUNA 2019",
    image: "assets/images/helmets/racing/agv/pista-gp-rr-min.png",
    price: "104999",
    offer: "20",
    rating: "5",
    ratingCount: "356",
    categoryName: "racing",
  },
  {
    _id: uuid(),
    name: "AGV AX8 EVO",
    description: "TRAIL GUNMETAL/ORANGE",
    image: "assets/images/helmets/off-road/agv/ax-8-evo-top-min.png",
    brand: "agv",
    inStock: true,
    fastDelivery: true,
    price: "23999",
    offer: "10",
    rating: "4",
    ratingCount: "452",
    categoryName: "offRoad",
  },
  {
    _id: uuid(),
    name: "AGV AX9 MULTI",
    description: "ECE DOT TOP - SOLELUNA 2019",
    image: "assets/images/helmets/off-road/agv/ax9-multi-min.png",
    brand: "agv",
    inStock: true,
    fastDelivery: false,
    price: "41999",
    offer: "15",
    rating: "4",
    ratingCount: "234",
    categoryName: "offRoad",
  },
  {
    _id: uuid(),
    name: "AGV SPORTMODULAR MULTI",
    description: "ECE DOT TOP - SOLELUNA 2019",
    image: "assets/images/helmets/touring/agv/sportmodular-multi-min.png",
    brand: "agv",
    inStock: false,
    fastDelivery: true,
    price: "65999",
    offer: "20",
    rating: "5",
    ratingCount: "650",
    categoryName: "touring",
  },
  {
    _id: uuid(),
    name: "ARAI GP7",
    description: "(FRP) RACE TESTED",
    image: "assets/images/helmets/racing/arai/gp-7-min.png",
    brand: "arai",
    inStock: false,
    fastDelivery: true,
    price: "71999",
    offer: "20",
    rating: "4",
    ratingCount: "512",
    categoryName: "racing",
  },
  {
    _id: uuid(),
    name: "ARAI QUANTIC",
    description: "HIGH-SPEED COMFORT",
    image: "assets/images/helmets/street/arai/quantic-min.png",
    brand: "arai",
    inStock: true,
    fastDelivery: true,
    price: "67999",
    offer: "20",
    rating: "4",
    ratingCount: "760",
    categoryName: "street",
  },
  {
    _id: uuid(),
    name: "ARAI URBAN-V",
    description: "LOOK COOL. STAY COOL",
    image: "assets/images/helmets/touring/arai/urban-v-min.png",
    brand: "arai",
    inStock: true,
    fastDelivery: true,
    price: "45999",
    offer: "15",
    rating: "3",
    ratingCount: "121",
    categoryName: "touring",
  },
  {
    _id: uuid(),
    name: "MT RAPID PRO",
    description: "PRO MASTER B5 GLOSS FLOUR RED",
    image: "assets/images/helmets/racing/mt/rapid-pro-b5-min.png",
    brand: "mt",
    inStock: true,
    fastDelivery: false,
    price: "27999",
    offer: "10",
    rating: "5",
    ratingCount: "440",
    categoryName: "racing",
  },
  {
    _id: uuid(),
    name: "MT TARGO CRAZYDOG",
    description: "CRAZYDOG G3 GLOSS FLOUR YELLOW",
    image: "assets/images/helmets/street/mt/targo-crazydog-min.png",
    brand: "mt",
    inStock: true,
    fastDelivery: true,
    price: "7899",
    offer: "10",
    rating: "4",
    ratingCount: "579",
    categoryName: "street",
  },
  {
    _id: uuid(),
    name: "MT FALCON ENERGY",
    description: "ENERGY B5 GLOSS RED",
    image: "assets/images/helmets/off-road/mt/falcon-energy-b5-min.png",
    brand: "mt",
    inStock: true,
    fastDelivery: true,
    price: "7299",
    offer: "10",
    rating: "5",
    ratingCount: "322",
    categoryName: "offRoad",
  },
  {
    _id: uuid(),
    name: "MT JET LEMANS",
    description: "TANT A5 MATT RED",
    image: "assets/images/helmets/touring/mt/jet-lemans2sv-min.png",
    brand: "mt",
    inStock: false,
    fastDelivery: true,
    price: "7599",
    offer: "10",
    rating: "4",
    ratingCount: "810",
    categoryName: "touring",
  },
  {
    _id: uuid(),
    name: "SHOEI X-FOURTEEN",
    description: "MATT BLACK",
    image: "assets/images/helmets/racing/shoei/x-fourteen-min.png",
    brand: "shoei",
    inStock: false,
    fastDelivery: false,
    price: "59999",
    offer: "15",
    rating: "5",
    ratingCount: "338",
    categoryName: "racing",
  },
  {
    _id: uuid(),
    name: "SHOEI VFX EVO",
    description: "MATT BLACK",
    image: "assets/images/helmets/off-road/shoei/vfx-evo-min.png",
    brand: "shoei",
    inStock: true,
    fastDelivery: true,
    price: "44999",
    offer: "15",
    rating: "4",
    ratingCount: "156",
    categoryName: "offRoad",
  },
  {
    _id: uuid(),
    name: "SHOEI GT AIR 2",
    description: "MATT BLACK",
    image: "assets/images/helmets/street/shoei/gt-air2-min.png",
    brand: "shoei",
    inStock: true,
    fastDelivery: false,
    price: "65999",
    offer: "15",
    rating: "5",
    ratingCount: "519",
    categoryName: "street",
  },
  {
    _id: uuid(),
    name: "SHOEI RF 1400",
    description: "MATT BLACK",
    image: "assets/images/helmets/street/shoei/rf-1400-min.png",
    brand: "shoei",
    inStock: false,
    fastDelivery: false,
    price: "55999",
    offer: "15",
    rating: "4",
    ratingCount: "784",
    categoryName: "street",
  },
  {
    _id: uuid(),
    name: "SHOEI HORNET X2",
    description: "MATT BLACK",
    image: "assets/images/helmets/touring/shoei/hornetx2-min.png",
    brand: "shoei",
    inStock: true,
    fastDelivery: true,
    price: "38999",
    offer: "15",
    rating: "4",
    ratingCount: "226",
    categoryName: "touring",
  },
];
